- name: Get namespace name
  hosts: localhost
  collections:
    - oracle.oci
  tasks:
    - name: Installing oci python library using Ansible pip module
      pip:
        name: oci
    - name: Get namespace name
      oci_object_storage_namespace_facts:
      register: output
    - name: Print namespace name
      debug:
        msg: "{{ output }}"
