---
- name: Install python sdk
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
  - name: Installing oci python library using Ansible pip module
    pip:
      name: oci
